version: "3.7"
services:

    app:
        build: .
        restart: always
        container_name: app
        volumes: 
            - ./src/storage/logs:/var/www/html/storage/logs
            - ./src/storage/app/public:/var/www/html/storage/app/public
            - ./src/.env:/var/www/html/.env
        ports:
            - "8000:80"
        networks:
            - app

networks:
    app:
        name: app
