name: latest

on:
  push:
    branches:
      - main

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Sign into Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build latest Docker image
        run: docker buildx build -t justintime50/nginx-php --platform linux/amd64,linux/arm/v7,linux/arm64 .
      - name: Push latest Image to Docker Hub
        run: docker push justintime50/nginx-php
