name: latest

on:
  push:
    branches:
      - main

jobs:
  latest-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Sign into Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker image
        run: docker build -t justintime50/nginx-php:latest --platform linux/amd64 .
      - name: Push image to Hub
        run: docker push justintime50/nginx-php:latest

  latest-arm-v7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Sign into Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker image
        run: docker build -t justintime50/nginx-php:latest --platform linux/arm/v7 .
      - name: Push image to Hub
        run: docker push justintime50/nginx-php:latest

  latest-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Sign into Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker image
        run: docker build -t justintime50/nginx-php:latest --platform linux/arm64 .
      - name: Push image to Hub
        run: docker push justintime50/nginx-php:latest
