name: release

on:
  push:
    tags:
      - '*'

jobs:
  release-amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.1', '8.2', '8.3', '8.4']
    steps:
      - uses: actions/checkout@v4
      - name: Sign into Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker image
        run: docker build -t justintime50/nginx-php:${{ matrix.php_version }}-${GITHUB_REF##*/} --build-arg PHP_VERSION=${{ matrix.php_version }} --platform linux/amd64 .
      - name: Push image to Hub
        run: docker push justintime50/nginx-php:${{ matrix.php_version }}-${GITHUB_REF##*/}

  release-arm-v7:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.1', '8.2', '8.3', '8.4']
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Sign into Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker image
        run: docker build -t justintime50/nginx-php:${{ matrix.php_version }}-${GITHUB_REF##*/} --build-arg PHP_VERSION=${{ matrix.php_version }} --platform linux/arm/v7 .
      - name: Push image to Hub
        run: docker push justintime50/nginx-php:${{ matrix.php_version }}-${GITHUB_REF##*/}

  release-arm64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.1', '8.2', '8.3', '8.4']
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Sign into Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker image
        run: docker build -t justintime50/nginx-php:${{ matrix.php_version }}-${GITHUB_REF##*/} --build-arg PHP_VERSION=${{ matrix.php_version }} --platform linux/arm64 .
      - name: Push image to Hub
        run: docker push justintime50/nginx-php:${{ matrix.php_version }}-${GITHUB_REF##*/}
