name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.4", "8.0", "8.1"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Install buildx
        uses: docker/setup-buildx-action@v1
      - name: Sign into Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker image and push to Docker Hub
        run: docker buildx build --push -t justintime50/nginx-php:${{ matrix.php_version }}-${GITHUB_REF##*/} --build-arg PHP_VERSION=${{ matrix.php_version }} --platform linux/amd64,linux/arm/v7,linux/arm64 .
