name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.4", "8.0"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t justintime50/nginx-php:${{ matrix.php_version }} --build-arg VERSION=${{ matrix.php_version }} .
          docker push justintime50/nginx-php:${{ matrix.php_version }}
